"""empty message

Revision ID: 0aa474a096aa
Revises: d76df4664c74
Create Date: 2025-02-19 14:21:28.218208

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '0aa474a096aa'
down_revision = 'd76df4664c74'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TextData', sa.Column('processed_urls_id', sa.Uuid(), nullable=True))
    op.drop_constraint('TextData_processed_urls_by_id_fkey', 'TextData', type_='foreignkey')
    op.create_foreign_key(None, 'TextData', 'ProcessedUrls', ['processed_urls_id'], ['id'], ondelete='SET NULL')
    op.drop_column('TextData', 'processed_urls_by_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TextData', sa.Column('processed_urls_by_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'TextData', type_='foreignkey')
    op.create_foreign_key('TextData_processed_urls_by_id_fkey', 'TextData', 'ProcessedUrls', ['processed_urls_by_id'], ['id'], ondelete='SET NULL')
    op.drop_column('TextData', 'processed_urls_id')
    # ### end Alembic commands ###
