"""empty message

Revision ID: e6453a4d5d8a
Revises: b6c929c5da8e
Create Date: 2025-03-11 07:11:25.817928

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'e6453a4d5d8a'
down_revision = 'b6c929c5da8e'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ProcessedUrls', sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_index('ix_ProcessedUrls_suf_url', table_name='ProcessedUrls')
    op.create_index(op.f('ix_ProcessedUrls_url'), 'ProcessedUrls', ['url'], unique=False)
    op.drop_column('ProcessedUrls', 'suf_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ProcessedUrls', sa.Column('suf_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_ProcessedUrls_url'), table_name='ProcessedUrls')
    op.create_index('ix_ProcessedUrls_suf_url', 'ProcessedUrls', ['suf_url'], unique=False)
    op.drop_column('ProcessedUrls', 'url')
    # ### end Alembic commands ###
