"""empty message

Revision ID: d76df4664c74
Revises: 6c7f404ecf7a
Create Date: 2025-02-19 14:12:02.919263

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'd76df4664c74'
down_revision = '6c7f404ecf7a'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('TextData_processed_urls_by_id_fkey', 'TextData', type_='foreignkey')
    op.create_foreign_key(None, 'TextData', 'ProcessedUrls', ['processed_urls_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'TextData', type_='foreignkey')
    op.create_foreign_key('TextData_processed_urls_by_id_fkey', 'TextData', 'ProcessedUrls', ['processed_urls_by_id'], ['id'])
    # ### end Alembic commands ###
