"""empty message

Revision ID: a4a73c3b0c25
Revises: be3e819eab6b
Create Date: 2025-02-19 12:39:45.320341

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'a4a73c3b0c25'
down_revision = 'be3e819eab6b'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ProcessedUrls', sa.Column('source_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.drop_constraint('ProcessedUrls_source_by_id_fkey', 'ProcessedUrls', type_='foreignkey')
    op.create_foreign_key(None, 'ProcessedUrls', 'Source', ['source_id'], ['id'])
    op.drop_column('ProcessedUrls', 'source_by_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ProcessedUrls', sa.Column('source_by_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ProcessedUrls', type_='foreignkey')
    op.create_foreign_key('ProcessedUrls_source_by_id_fkey', 'ProcessedUrls', 'Source', ['source_by_id'], ['id'])
    op.drop_column('ProcessedUrls', 'source_id')
    # ### end Alembic commands ###
